# Site settings
title: Nipun Agarwala blog
email: 
description: "Exploration of a student "
baseurl: ""
url: "http://nipunblog.github.io"

github_username:  nipunagarwala

# Build settings
markdown: redcarpet
permalink: pretty
